site_name: pinax-calendars
pages:
- [index.md, Home]
- [usage.md, Usage]
- [changelog.md, Change Log]
theme: readthedocs
repo_url: https://github.com/pinax/pinax-calendars
site_description: "Django utilities for publishing events as a calendar"
site_author: "Pinax Team"
markdown_extensions: [admonition]
